app:
  fwAppId: ${FW_APP_ID:default}  # uses APP_NAME env var or "MyDefaultApp" as default
  fwUserName: ${FW_USER_NAME:default}
  fwKey: ${FW_KEY:default}
  fwHost: ${FW_HOST:default}
  fwPort: ${FW_PORT:default}
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientServletAutoConfiguration
  config:
    activate:
      on-profile: test

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:4445/admin/oauth2/introspect
          client-id: ab8389ca-bc5b-48a2-9dfd-3788950d340d
          client-secret: secret